### ISSUE TITLE
cant get this working

### ISSUE THREAD

**Issue by jamiemc71** [BryceCanyonCounty/bcc-doorlocks#10]
hey there, i downloaded this script and put the DB in and my steam id into the config but i cant get it to work.

i see the /createDoor command but when i point my gun and press G nothing seems to work.
i run the lastest download of the script along with the all the depens it requires,

any idea what could be wrong please

**Comment by jakeyboi1** [comment]
Here are some possible reasons why, that I can think of. 1. Not set as admin in config. 2. Your restarting the resource/ensuring it live instead of in your resources.cfg file.

**Comment by jamiemc71** [comment]
> 

thanks for your reply.
i have set the admin with my steam ID and i have it ensured and restarted the hole server but still nothing seems to happen, i can see the comment which indurates to me that the script is in but nothing seems to happen past the command
