### ISSUE TITLE
Cell doors

### ISSUE THREAD

**Issue by Cookiiilove** [BryceCanyonCounty/bcc-doorlocks#32]
I am trying to lock cell doors in each of the police stations, but the selector does not seem to recognise the cell doors only the main doors into the building. is there a work around?

**Comment by Fistsofury** [comment]
> I am trying to lock cell doors in each of the police stations, but the selector does not seem to recognise the cell doors only the main doors into the building. is there a work around?

When you create the doors for cells, it seems to pull another prop. use spooni to check the correct prop name and you can manually change it into the database where the doorlocks save. then reboot the server.
