### ISSUE TITLE
error finding iterator for doorlock 

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-doorlocks#35]
seems to be causing a issue with creating houses or doors in general because it doesn't show that a door is there when you try to set one, for housing aim at it or press e doesn't work sends back this error in f8 console but not on tx console... unless its feather menu or housing causing that error but my assumption based on what its stating is the doorlocks
![20240913233252_1](https://github.com/user-attachments/assets/b8eba9fd-12ee-46c2-974e-a989b3496d5b)

**Comment by iseeyoucopy** [comment]
I think that door doesnt exist in doorhashes.lua thats why you have that erroor, but ill double check myself

**Comment by yaboibutt3r** [comment]
ahh, very possible. I didn't actually think about that I just had the issue for multiple doors but they could've been doors on added ymaps didn't look into it much. Just sent after I got the error on a couple doors. ill try it on some I know should work. sorry for any possible inconveniences.

**Comment by AndrewR3K** [comment]
@yaboibutt3r Did that resolve the issue for you? If so I will be closing out this ticket. 

Thanks!

**Comment by yaboibutt3r** [comment]
@AndrewR3K you see I'm a idiot and forgot to change the steam identifier so I haven't had that issue anymore but after I changed it I was still getting a error.. but I'm gonna update it first now and see if that continues

**Comment by yaboibutt3r** [comment]
so this is the error I'm getting now, I just updated and went to a door that's put in the door hashes and it still doesn't want to work for me lol
![218_14](https://github.com/user-attachments/assets/aa8566e6-6953-4076-b21a-f50d17bc58cc)

**Comment by AndrewR3K** [comment]
Did you restart the script and server after adding the doorhash?

**Comment by yaboibutt3r** [comment]
uhh after updating the script I restarted the server, looked in the doorhashes.lua for a door that is already in there and tried but that's the error I got, door locks used to work for me until recently and im not exactly sure why
